services:
  sftp-server:
    build:
      context: .
      dockerfile: ./sftp-server/Dockerfile
    container_name: sftp-server
    hostname: sftp-server
    privileged: true
    command: /sbin/init
    ports:
      - "22:22"
  rclone-server:
    build:
      context: .
      dockerfile: ./rclone-server/Dockerfile
    container_name: rclone-server
    hostname: rclone-server
    tty: true
    env_file:
      - ./rclone-server/rclone.env
  S3:
    image: localstack/localstack:2.0.0
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_DEFAULT_REGION=ap-northeast-1
    volumes:
      - ./S3/ready/:/etc/localstack/init/ready.d
