services:
  sftp-server:
    build:
      context: .
      dockerfile: ./sftp-server/Dockerfile
    container_name: sftp-server
    hostname: sftp-server
    privileged: true
    command: /sbin/init
    ports:
      - "22:22"
  rclone-server:
    build:
      context: .
      dockerfile: ./rclone-server/Dockerfile
    container_name: rclone-server
    hostname: rclone-server
    tty: true
    env_file:
      - ./rclone-server/sftp-connection.env
